[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Redirect API requests to our serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# For single page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 