[build]
  base = "."
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  VITE_SKIP_TS_CHECK = "true"
  NODE_ENV = "development"

[functions]
  directory = "netlify/functions"

# Plugin to automatically install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect API requests to our serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# For single page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 